FilderNET/FilderNET/FilderNET.Web/Controllers/PersonalController.cs
using FilderNET.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FilderNET.Web.Controllers
{
    public class PersonalController : Controller
    {
        // GET: Personal
        public ActionResult Index()
        {
            return View(DataManager.GetAllUsuarios());
        }

        public ActionResult AltaPersona()
        {
            ViewBag.PERSONAL = convert(DataManager.GetAllUsuarios());
            CargarJerarquias();
            
            return View();
        }

        private void CargarJerarquias()
        {
            List<SelectListItem> selectListItemsJerarquia = new List<SelectListItem>();

            selectListItemsJerarquia.Add(new SelectListItem { Value = "1", Text = "PROMOTOR" });
            selectListItemsJerarquia.Add(new SelectListItem { Value = "2", Text = "SUPERVISOR" });
            selectListItemsJerarquia.Add(new SelectListItem { Value = "3", Text = "LIDER" });

            if ((bool)Session["BAN_MASTER"] || (bool)Session["BAN_SISTEMAS"] || (bool)Session["BAN_DUENO"])
            {
                selectListItemsJerarquia.Add(new SelectListItem { Value = "4", Text = "MASTER" });
                selectListItemsJerarquia.Add(new SelectListItem { Value = "7", Text = "ADMINISTRATIVO" });
            }

            if ((bool)Session["BAN_SISTEMAS"])
            {
                selectListItemsJerarquia.Add(new SelectListItem { Value = "6", Text = "SISTEMAS" });
                selectListItemsJerarquia.Add(new SelectListItem { Value = "5", Text = "DUEÑO" });
            }
            ViewBag.JERARQUIAS = selectListItemsJerarquia;
        }

        /// <summary>
        /// Método que genera una cadena aleatorea del un tamaño deceado.
        /// </summary>
        /// <param name="length"></param>
        /// <returns></returns>
        private static string GetRandomString(int length)
        {
            Random random = new Random();
            const string chars = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        [HttpPost]
        //public ActionResult SavePersona([Bind(Include = "USUARIO,CONTRASENA,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE,CURP,RFC,TELEFONO,EMAIL,ACTIVO,SUPERVISOR_SELECTED,FECHA_NACIMIENTO")] ModeloUsuarios modeloUsuario)
        public ActionResult SavePersona(ModeloUsuarios modeloUsuario, HttpPostedFileBase somefile)
        {
            string pathPhoto = string.Empty;
            string filename = string.Empty;
            if (somefile != null && somefile.ContentLength > 0)
            {
                filename = Path.GetFileName(somefile.FileName);
                pathPhoto = Path.Combine(Server.MapPath("~/assets/images/users/"), filename);

                if (System.IO.File.Exists(pathPhoto))
                {
                    string[] vec = filename.Split('.');
                    string nombre = vec[0];
                    string ext = vec[1];

                    string rand =GetRandomString(3);
                    filename = nombre + "_" + rand + "." +  ext;
                    pathPhoto = Path.Combine(Server.MapPath("~/assets/images/users/"), filename);
                    while (System.IO.File.Exists(pathPhoto))
                    {
                        rand = GetRandomString(3);
                        filename = nombre + "_" + rand + "." + ext;
                        pathPhoto = Path.Combine(Server.MapPath("~/assets/images/users/"), filename);
                    }
                    
                    MemoryStream memoryStream = new MemoryStream();
                    somefile.InputStream.CopyTo(memoryStream);
                    byte[] data = memoryStream.ToArray();

                    System.IO.File.WriteAllBytes(pathPhoto, data);

                }
                else
                {
                    somefile.SaveAs(pathPhoto);
                }
                
            }

            modeloUsuario.ID_JERARQUIA = Convert.ToInt32(modeloUsuario.JERARQUIA_SELECTED);
            modeloUsuario.ID_JEFE = Convert.ToInt32(modeloUsuario.SUPERVISOR_SELECTED);

            if (!string.IsNullOrWhiteSpace(filename))
            {
                modeloUsuario.FOTO = "~/assets/images/users/" + filename;
            }
            
            int r = DataManager.SetNewUsuario(modeloUsuario);

            if (r>0)
                return View("Index", DataManager.GetAllUsuarios());
            else
                return View("AltaPersona");
        }

        public ActionResult SaveChangePersona([Bind(Include = "ID_USUARIO,ID_JERARQUIA,USUARIO,APELLIDO_PATERNO,APELLIDO_MATERNO,NOMBRE,CURP,RFC,TELEFONO,EMAIL,ACTIVO,SUPERVISOR_SELECTED,FECHA_NACIMIENTO,JERARQUIA_SELECTED")] ModeloUsuarios modeloUsuario)
        {
            modeloUsuario.ID_JEFE = Convert.ToInt32(modeloUsuario.SUPERVISOR_SELECTED);
            modeloUsuario.ID_JERARQUIA = Convert.ToInt32(modeloUsuario.JERARQUIA_SELECTED);
            int r = DataManager.UpdateDataUsuario(modeloUsuario);
            
            if (r > 0)
                return View("Index", DataManager.GetAllUsuarios());
            else
            {
                ModeloUsuarios modelo = DataManager.GetUsuario(modeloUsuario.ID_USUARIO);
                modelo.SUPERVISOR_SELECTED = Convert.ToString(modelo.ID_JEFE);
                modelo.JERARQUIA_SELECTED = Convert.ToString(modelo.ID_JERARQUIA);
                ViewBag.PERSONAL = convert(DataManager.GetAllUsuarios());

                return View("EditPersona", modelo);
            }  
        }
        
        public ActionResult EditPersona(int idUsuario)
        {
            ModeloUsuarios modelo = DataManager.GetUsuario(idUsuario);
            modelo.SUPERVISOR_SELECTED = Convert.ToString(modelo.ID_JEFE);
            modelo.JERARQUIA_SELECTED = Convert.ToString(modelo.ID_JERARQUIA);
            ViewBag.PERSONAL = convert(DataManager.GetAllUsuarios());
            CargarJerarquias();

            return View(modelo);
        }

        private List<SelectListItem> convert(List<ModeloUsuarios> usuarios)
        {
            List<SelectListItem> selectListItems = new List<SelectListItem>();

            foreach (var item in usuarios)
            {
                SelectListItem selectListItem = new SelectListItem();

                selectListItem.Text = item.NOMBRE + " " + item.APELLIDO_PATERNO + " " + item.APELLIDO_MATERNO;
                selectListItem.Value = item.ID_USUARIO.ToString();
                
                selectListItems.Add(selectListItem);
            }

            return selectListItems;
        }

        
    }
}

FilderNET/FilderNET/FilderNET.Web/Views/Personal/AltaPersona.cshtml
@model FilderNET.Web.Models.ModeloUsuarios

@{
    ViewBag.Title = "AltaPersona";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Alta de persona</h2>

<div class="row">
    <div class="col-lg-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h4>Datos de la persona</h4>
                <p class="text-muted m-b-30 font-14">
                    Por favor ingrese los datos de la persona.
                </p>
                @{
        //using (Html.BeginForm("SavePersona", "Personal", Model, FormMethod.Post, new { enctype = "multipart/form-data" }))
        using (Html.BeginForm("SavePersona", "Personal", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">NOMBRE</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>


            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">APELLIDO PATERNO</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.APELLIDO_PATERNO, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">APELLIDO MATERNO</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.APELLIDO_MATERNO, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">USUARIO</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">CONTRASEÑA</label>
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.CONTRASENA, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">FECHA NACIMIENTO</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FECHA_NACIMIENTO, new { htmlAttributes = new { @class = "form-control", @id = "datepicker-autoclose-fechaelaboracion" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">CURP</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CURP, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">RFC</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RFC, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">TELÉFONO</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">EMAIL</label>
                <div class="col-md-10">
                    @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">JERARQUÍA</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.JERARQUIA_SELECTED, new SelectList(ViewBag.JERARQUIAS, "Value", "Text"), new { @class = "form-control m-bot15" })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">SUPERVISOR</label>
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SUPERVISOR_SELECTED, new SelectList(ViewBag.PERSONAL, "Value", "Text"), new { @class = "form-control m-bot15" })
                </div>
            </div>

            <div class="form-group row">
                <label for="example-text-input" class="col-sm-2 col-form-label">ACTIVO</label>
                <div class="col-md-10">
                    @Html.CheckBoxFor(model => model.ACTIVO)
                </div>
            </div>

            <div>
                <label for="example-text-input" class="col-sm-2 col-form-label">FOTO</label>
                <div class="col-md-10">
                    <input type="file" name="somefile" />
                </div>
            </div>

            <div class="form-group">
                <div>
                    <button type="submit" class="btn btn-primary waves-effect waves-light">
                        Guardar
                    </button>
                </div>
            </div>
}
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <!-- jQuery  -->
    <script src="@Url.Content("~/assets/js/jquery.slimscroll.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.blockUI.js")"></script>

    <!-- Plugins js -->
    <script src="@Url.Content("~/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>

    <!-- Plugins Init js -->
    <script src="@Url.Content("~/assets/pages/form-advanced.js")"></script>
}

FilderNET/FilderNET/FilderNET.Web/Views/Personal/EditPersona.cshtml
@model FilderNET.Web.Models.ModeloUsuarios

@{
    ViewBag.Title = "EditPersona";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar datos</h2>

<div class="row">
    <div class="col-lg-12">
        <div class="card m-b-30">
            <div class="card-body">
                <h4>Datos de la persona</h4>
                <p class="text-muted m-b-30 font-14">
                    Por favor ingrese los datos de la persona.
                </p>
                @{
                    using (Html.BeginForm("SaveChangePersona", "Personal", Model, FormMethod.Post))
                    {

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">NOMBRE</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.NOMBRE, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>


                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">APELLIDO PATERNO</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.APELLIDO_PATERNO, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">APELLIDO MATERNO</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.APELLIDO_MATERNO, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">USUARIO</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">FECHA NACIMIENTO</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.FECHA_NACIMIENTO, new { htmlAttributes = new { @class = "form-control", @id = "datepicker-autoclose-fechaelaboracion" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">CURP</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.CURP, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">RFC</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.RFC, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">TELÉFONO</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.TELEFONO, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">EMAIL</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.EMAIL, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">JERARQUÍA</label>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.JERARQUIA_SELECTED, new SelectList(ViewBag.JERARQUIAS, "Value", "Text"), new { @class = "form-control m-bot15" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">SUPERVISOR</label>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.SUPERVISOR_SELECTED, new SelectList(ViewBag.PERSONAL, "Value", "Text"), new { @class = "form-control m-bot15" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="example-text-input" class="col-sm-2 col-form-label">ACTIVO</label>
                            <div class="col-md-10">
                                @Html.CheckBoxFor(model => model.ACTIVO)
                            </div>
                        </div>

                        <div class="form-group">
                            <div>
                                <button type="submit" class="btn btn-primary waves-effect waves-light">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
    {
    <!-- jQuery  -->
    <script src="@Url.Content("~/assets/js/jquery.slimscroll.js")"></script>
    <script src="@Url.Content("~/assets/js/jquery.blockUI.js")"></script>

    <!-- Plugins js -->
    <script src="@Url.Content("~/assets/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/assets/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js")" type="text/javascript"></script>

    <!-- Plugins Init js -->
    <script src="@Url.Content("~/assets/pages/form-advanced.js")"></script>
}

FilderNET/FilderNET/FilderNET.Web/Views/Personal/Index.cshtml
@model IEnumerable<FilderNET.Web.Models.ModeloUsuarios>

@{
    ViewBag.Title = "Personal";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card m-b-30">
            <div class="card-body">
                <table id="datatable-buttons" class="table table-striped table-bordered" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.NOMBRE)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.APELLIDO_PATERNO)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.APELLIDO_MATERNO)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.USUARIO)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CURP)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RFC)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TELEFONO)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EMAIL)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ACTIVO)
                            </th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NOMBRE)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.APELLIDO_PATERNO)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.APELLIDO_MATERNO)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.USUARIO)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CURP)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.RFC)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TELEFONO)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EMAIL)
                                </td>
                                @{
                                    if (item.ACTIVO)
                                    {
                                        <td><span class="badge badge-success">Activo</span></td>
                                    }
                                    else
                                    {
                                        <td><span class="badge badge-danger">No Activo</span></td>
                                    }
                                }

                                <td>
                                    <div>
                                        <a href="@Url.Action("EditPersona","Personal", new { idUsuario =  item.ID_USUARIO })" class="btn btn-info waves-effect waves-light">Editar</a>
                                        @*<a href="@Url.Action("","")" class="btn btn-danger waves-effect waves-light">Eliminar</a>*@
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <!-- Required datatable js -->
    <script src="@Url.Content("~/assets/plugins/datatables/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.bootstrap4.min.js")"></script>
    <!-- Buttons examples -->
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.buttons.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.bootstrap4.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/jszip.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/pdfmake.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/vfs_fonts.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.html5.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.print.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/buttons.colVis.min.js")"></script>
    <!-- Responsive examples -->
    <script src="@Url.Content("~/assets/plugins/datatables/dataTables.responsive.min.js")"></script>
    <script src="@Url.Content("~/assets/plugins/datatables/responsive.bootstrap4.min.js")"></script>

    <!-- Datatable init js -->
    <script src="@Url.Content("~/assets/pages/datatables.init.js")"></script>
}